# Generated by Django 3.2.10 on 2022-07-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20220715_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='time_comment',
        ),
    ]
