# Generated by Django 3.2.10 on 2022-07-15 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_commentmodel_time_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='reply_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.commentmodel'),
        ),
    ]
