# Generated by Django 3.2.10 on 2022-07-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_commentmodel_reply_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='reply_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.commentmodel'),
        ),
    ]
