# Generated by Django 3.2.10 on 2022-07-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_commentmodel_reply_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='reply_of',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
