# Generated by Django 3.2.10 on 2022-07-29 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_alter_commentmodel_reply_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='time_edit',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
