# Generated by Django 3.2.10 on 2022-08-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_commentmodel_time_edit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='commentmodel',
            table='tbl_comment',
        ),
    ]
