# Generated by Django 3.2.10 on 2022-07-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_it', '0003_auto_20220701_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvotemodel',
            name='view_upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
