# Generated by Django 3.2.10 on 2022-07-04 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_it', '0004_auto_20220704_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='time_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
