# Generated by Django 3.2.10 on 2022-07-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_it', '0006_auto_20220704_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
