# Generated by Django 3.2.10 on 2022-07-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_it', '0007_blogmodel_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='time_read',
            field=models.CharField(default=5, max_length=30),
        ),
    ]
