# Generated by Django 3.2.10 on 2022-07-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_it', '0008_blogmodel_time_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
