# Generated by Django 3.2.10 on 2022-07-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20220713_1039'),
        ('blog_it', '0012_alter_blogmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvotemodel',
            name='forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvote_series', to='forum.forummodel'),
        ),
    ]
