# Generated by Django 3.2.10 on 2022-07-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forummodel_tag'),
        ('blog_it', '0013_upvotemodel_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotemodel',
            name='forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_blog', to='forum.forummodel'),
        ),
    ]
