# Generated by Django 3.2.10 on 2022-07-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_forummodel_stt'),
        ('blog_it', '0016_upvotemodel_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotemodel',
            name='forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_upvote', to='forum.forummodel'),
        ),
    ]
