# Generated by Django 3.2.10 on 2022-07-26 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_alter_commentmodel_reply_of'),
        ('blog_it', '0017_alter_upvotemodel_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvotemodel',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_forum', to='comment.commentmodel'),
        ),
    ]
