# Generated by Django 3.2.10 on 2022-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_it', '0019_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
