# Generated by Django 3.2.10 on 2022-08-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_it', '0021_auto_20220729_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='blogtagmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bookmarks',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='seriesblogmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='seriesmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='upvotemodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogtagmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seriesblogmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='upvotemodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='blogmodel',
            table='tbl_blog',
        ),
        migrations.AlterModelTable(
            name='blogtagmodel',
            table='tbl_blog_tags',
        ),
        migrations.AlterModelTable(
            name='bookmarks',
            table='tbl_bookmarks',
        ),
        migrations.AlterModelTable(
            name='seriesblogmodel',
            table='tbl_series_blog',
        ),
        migrations.AlterModelTable(
            name='seriesmodel',
            table='tbl_series',
        ),
        migrations.AlterModelTable(
            name='upvotemodel',
            table='tbl_upvote',
        ),
    ]
