# Generated by Django 3.2.10 on 2022-08-16 06:49

from django.db import migrations, models
import django.db.models.deletion

create_table_technical_tbl = """
    CREATE TABLE `technical_tbl` (
    id bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title nvarchar(256) not null unique,
    user_id bigint not null,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user_createusermodel (id)
    ) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('user', '0001_initial')
    ]

    operations = [
        migrations.RunSQL(create_table_technical_tbl)
    ]
