# Generated by Django 3.2.10 on 2022-08-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('technical', '0001_inventory_name_capitalize'), ('technical', '0002_tagtechnicalmodel'), ('technical', '0003_alter_tagtechnicalmodel_table')]

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='\n    CREATE TABLE `technical_tbl` (\n    id bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,\n    title nvarchar(256) not null unique,\n    user_id bigint not null,\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n    FOREIGN KEY (user_id) REFERENCES user_createusermodel (id)\n    ) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n',
        ),
        migrations.CreateModel(
            name='TagTechnicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'technical',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='tagtechnicalmodel',
            table='technical_tbl',
        ),
    ]
