# Generated by Django 3.2.10 on 2022-08-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technical', '0001_inventory_name_capitalize'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTechnicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'technical',
                'managed': False,
            },
        ),
    ]
