# Generated by Django 3.2.10 on 2022-08-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0002_tagtechnicalmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tagtechnicalmodel',
            table='technical_tbl',
        ),
    ]
