# Generated by Django 3.2.10 on 2022-07-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createusermodel',
            name='rank',
            field=models.CharField(default='member', max_length=30),
            preserve_default=False,
        ),
    ]
