# Generated by Django 3.2.10 on 2022-07-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_createusermodel_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='createusermodel',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
