# Generated by Django 3.2.10 on 2022-07-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_createusermodel_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusermodel',
            name='rank',
            field=models.CharField(choices=[('Thành viên mới', 'Lv1'), ('Người dùng', 'Lv2'), ('Người dùng nổi bật', 'Lv3'), ('Fan cứng', 'Lv4'), ('Người có tầm ảnh hưởng', 'Lv5'), ('Quản trị viên', 'Lv6')], default='Thành viên mới', max_length=30),
        ),
    ]
