# Generated by Django 3.2.10 on 2022-07-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_createusermodel_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='createusermodel',
            name='is_report',
            field=models.BooleanField(default=False),
        ),
    ]
