# Generated by Django 3.2.10 on 2022-07-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_createusermodel_is_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='createusermodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
    ]
