# Generated by Django 3.2.10 on 2022-07-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_createusermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createusermodel',
            name='sex',
            field=models.CharField(choices=[('Nam', 'Male'), ('Nữ', 'Female'), ('Khác', 'Orther'), ('Bí mật', 'Secret')], default='Nam', max_length=30),
        ),
    ]
