# Generated by Django 3.2.10 on 2022-07-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_createusermodel_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='user_name',
            field=models.CharField(default='Người mới', max_length=150, null=True, unique=True),
        ),
    ]
