# Generated by Django 3.2.10 on 2022-07-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220707_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusermodel',
            name='image',
            field=models.ImageField(default='20', upload_to='', verbose_name='image'),
            preserve_default=False,
        ),
    ]
