# Generated by Django 3.2.10 on 2022-07-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_createusermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
