# Generated by Django 3.2.10 on 2022-07-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2022-2-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='muted',
            field=models.BooleanField(default=False),
        ),
    ]
