# Generated by Django 3.2.10 on 2022-07-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_follow_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2022-1-1'),
            preserve_default=False,
        ),
    ]
