# Generated by Django 3.2.10 on 2022-07-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_follow_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='muted',
        ),
    ]
