# Generated by Django 3.2.10 on 2022-07-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_follow_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='follow',
            name='muted',
            field=models.BooleanField(default=False),
        ),
    ]
