# Generated by Django 3.2.10 on 2022-07-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20220714_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='from_user',
            new_name='follow_to',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='to_user',
            new_name='follower',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follow_to', 'follower')},
        ),
    ]
