# Generated by Django 3.2.10 on 2022-07-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20220714_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='createusermodel',
            name='home',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
