# Generated by Django 3.2.10 on 2022-07-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20220715_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusermodel',
            name='rank',
            field=models.CharField(choices=[('Thành viên mới', 'Lv1'), ('Người dùng', 'Lv2'), ('Tác giả', 'Lv3'), ('Fan cứng', 'Lv4'), ('Người có tầm ảnh hưởng', 'Lv5'), ('Chuyên gia bình luận', 'Lv6'), ('Quản trị viên', 'Lv7')], default='Thành viên mới', max_length=30),
        ),
    ]
