# Generated by Django 3.2.10 on 2022-08-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_createusermodel_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createusermodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email add'),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='rank',
            field=models.CharField(choices=[('Thành viên mới', 'Thành viên mới'), ('Người dùng', 'Người dùng'), ('Tác giả', 'Tác giả'), ('Fan cứng', 'Fan cứng'), ('Người có tầm ảnh hưởng', 'Người có tầm ảnh hưởng'), ('Chuyên gia bình luận', 'Chuyên gia bình luận'), ('Quản trị viên', 'Quản trị viên')], default='Thành viên mới', max_length=30),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='sex',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác'), ('Bí mật', 'Bí mật'), ('', '')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='user_name',
            field=models.CharField(default='Thành viên mới!', max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='createusermodel',
            unique_together={('email',)},
        ),
        migrations.AlterModelTable(
            name='createusermodel',
            table='tbl_user',
        ),
        migrations.AlterModelTable(
            name='follow',
            table='tbl_user_follow',
        ),
    ]
