# Generated by Django 3.2.10 on 2022-05-26 08:06

from django.db import migrations


def value_lend(apps, schema_editor):
    CategoryModel = apps.get_model('categorys', 'CategoryModel')
    categories = CategoryModel.objects.create(
       id=11,
       name='Tutorial',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(value_lend)
    ]
