# Generated by Django 3.2.10 on 2022-08-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_auto_20220701_1033'),
        ('categorys', '0003_auto'),
    ]

    operations = [
    ]
