# Generated by Django 3.2.10 on 2022-08-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0004_merge_0002_auto_20220701_1033_0003_auto'),
    ]

    operations = [
    ]
