# Generated by Django 3.2.10 on 2022-08-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0005_inventory_name_capitalize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=''),
        ),
        migrations.AlterModelTable(
            name='categorymodel',
            table='tbl_category',
        ),
    ]
