# Generated by Django 3.2.10 on 2022-07-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_it', '0013_upvotemodel_forum'),
        ('forum', '0003_auto_20220713_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummodel',
            name='tag',
            field=models.ManyToManyField(related_name='forum_tag', to='blog_it.BlogTagModel'),
        ),
    ]
