# Generated by Django 3.2.10 on 2022-07-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_forummodel_stt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
