# Generated by Django 3.2.10 on 2022-07-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_forummodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='forummodel',
            name='notify',
            field=models.TextField(null=True),
        ),
    ]
