# Generated by Django 3.2.10 on 2022-07-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20220725_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummodel',
            name='bookmarks',
            field=models.BooleanField(default=False),
        ),
    ]
