# Generated by Django 3.2.10 on 2022-07-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_remove_forummodel_bookmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forummodel',
            old_name='time_post',
            new_name='time_edit',
        ),
        migrations.AlterField(
            model_name='forummodel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
