# Generated by Django 3.2.10 on 2022-08-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20220729_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='forummodel',
            name='notify',
            field=models.TextField(blank=True, null=True),
        ),
    ]
