# Generated by Django 3.2.10 on 2022-08-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20220812_0710'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forummodel',
            table='tbl_forum',
        ),
    ]
