# Generated by Django 3.2.10 on 2022-08-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_forummodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forummodel',
            options={'ordering': ['id']},
        ),
    ]
