# Generated by Django 3.2.10 on 2022-09-30 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0008_auto_20220819_0645'),
        ('user', '0002_alter_createusermodel_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('link', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_fr_user', to=settings.AUTH_USER_MODEL)),
                ('to_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_to_comment', to='comment.commentmodel')),
                ('to_follow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_to_follow', to='user.follow')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_notifications',
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
