# Generated by Django 3.2.10 on 2022-09-30 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_alter_forummodel_options'),
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='to_forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_to_forum', to='forum.forummodel'),
        ),
    ]
